AllCops:
  Exclude:
    - 'bin/**/*'
    - config/initializers/devise.rb

Metrics/LineLength:
  Max: 120

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Max: 35

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/MethodLength:
  Max: 15
