# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
# https://thoughtbot.com/blog/circleci-2-rails

---
version: 2
jobs:
  build:
    working_directory: ~/portfolio
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          # PGUSER: portfolio_test
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: portfolio
          POSTGRES_DB: portfolio_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Dependencies from Cache
      - restore_cache:
          name: Restore bundle cache
          key: portfolio-{{ checksum "Gemfile.lock" }}

      # https://discuss.circleci.com/t/using-bundler-2-0-during-ci-fails/27411
      - run: sudo gem update --system
      - run: sudo gem uninstall bundler
      - run: sudo rm /usr/local/bin/bundle
      - run: sudo rm /usr/local/bin/bundler
      - run: sudo gem install bundler

      # Install Ruby dependencies
      - run: bundle check --path vendor/bundle || bundle install --deployment

      # Cache Dependencies
      - save_cache:
          name: Store bundle cache
          key: portfolio-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          key: portfolio-yarn-{{ checksum "yarn.lock" }}

      - run: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: portfolio-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
