default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: portfolio
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test
  username: portfolio

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
